Add a loop for patch statement
Signed-off-by: Sergen Yalçın <yalcinsergen97@gmail.com>

diff --git a/internal/templates/02-import.yaml.tmpl b/internal/templates/02-import.yaml.tmpl
--- a/internal/templates/02-import.yaml.tmpl
+++ b/internal/templates/02-import.yaml.tmpl
@@ -23,12 +23,6 @@ commands:
           echo "$endpoint - Ports present"
         fi
       done
-
-      if ${KUBECTL} get managed ; then
-          return 0
-      else
-          return 1
-      fi
     }
 
     attempt=1
@@ -45,13 +39,57 @@ commands:
     done
 
     exit 1
+- script: |
+    #!/bin/bash
+
+    function patch {
+        kindgroup=$1
+        name=$2
+        if ${KUBECTL} --subresource=status patch "$kindgroup/$name" --type=merge -p '{"status":{"conditions":[]}}' ; then
+            return 0
+        else
+            return 1
+        fi
+    }
+
+    attempt=1
+    max_attempts=10
+
+    # Array of resources
+    resources=(
 {{- range $resource := .Resources }}
 {{- if eq $resource.KindGroup "secret." -}}
   {{continue}}
 {{- end -}}
 {{- if not $resource.Namespace }}
-- command: ${KUBECTL} --subresource=status patch {{ $resource.KindGroup }}/{{ $resource.Name }} --type=merge -p '{"status":{"conditions":[]}}'
-- script: ${KUBECTL} annotate {{ $resource.KindGroup }}/{{ $resource.Name }} uptest-old-id=$(${KUBECTL} get {{ $resource.KindGroup }}/{{ $resource.Name }} -o=jsonpath='{.status.atProvider.id}') --overwrite
+        "{{ $resource.KindGroup }}/{{ $resource.Name }}"
 {{- end }}
 {{- end }}
+    )
+
+    for resource in "${resources[@]}"; do
+        kindgroup=$(echo "$resource" | cut -d '/' -f 1)
+        name=$(echo "$resource" | cut -d '/' -f 2)
+
+        attempt=1
+        while [[ $attempt -le $max_attempts ]]; do
+            if patch "$kindgroup" "$name"; then
+                echo "Successfully patched $kindgroup/$name"
+                ${KUBECTL} annotate "$kindgroup/$name" uptest-old-id=$(${KUBECTL} get "$kindgroup/$name" -o=jsonpath='{.status.atProvider.id}') --overwrite
+                break
+            else
+                printf "Retrying... (%d/%d) for %s/%s\n" "$attempt" "$max_attempts" "$kindgroup" "$name" >&2
+            fi
+            ((attempt++))
+            sleep 5
+        done
+
+        if [[ $attempt -gt $max_attempts ]]; then
+            echo "Failed to patch $kindgroup/$name after $max_attempts attempts"
+            exit 1
+        fi
+    done
+
+    echo "All resources patched successfully."
+    exit 0
 - command: ${KUBECTL} annotate managed --all crossplane.io/paused=false --overwrite
